@startuml
autonumber

main -[#red]>o os: os.Getenv(key)
os -->o main: svcEnv

service -[#red]> wiecfg: GetSvcParms(svc)
wiecfg -->o service: svcParms

service -[#red]> wiecfg: GetSvcEnvParms(svc,  svcEnv)
wiecfg --> service: svcEnvParms

service -[#red]> wiecfg: GetSvcEnvCredentials(svc,  svcEnv)
wiecfg --> service: svcCredentials

main -[#blue]> config: config.GetSvcLocalParms(svc,  svcEnv)
config --> main: svcEnvLocalParms

main -[#blue]> config: config.IntegrateParmsCredentials(parms,  envParms, svcEnvLocalParms, svcCredentials)
config --> main: svcParmsCreds
@enduml